### ISSUE TITLE
How to use Phonograph, Could you give me an example app please

### ISSUE THREAD

**Issue by donly** [yarrcc/Phonograph#1]
Actually I wrote an sample app, but it didn't work, here is the snippet code:

```swift
let description = AudioStreamBasicDescription(mSampleRate: 44100.0,
                                                      mFormatID: kAudioFormatLinearPCM,
                                                      mFormatFlags:kLinearPCMFormatFlagIsSignedInteger
                                                        | kLinearPCMFormatFlagIsPacked,
                                                      mBytesPerPacket: 2,
                                                      mFramesPerPacket: 1,
                                                      mBytesPerFrame: 2,
                                                      mChannelsPerFrame: 1,
                                                      mBitsPerChannel: 16,
                                                      mReserved: 0)
        do {
            try recordingQueue = PhonographInputQueue(asbd: description, callback: { (data) in
                print(data)
            })
            try recordingQueue.start()
            recordButton.setTitle("Stop", for: .normal)
        } catch {
            self.displayError("Failed")
        }
```

I have grant the app record permission, and start record using the above code, but nothing happens.
Did I make any mistakes?

Thanks.
Don

**Comment by asfdfdfd** [comment]
I want to start with small warning. This library is not maintained. Actually it should not be considered as complete solution, just as sample to write your own code for Audio Queues. This project is dropped (at least for now) in favor of Audio Units.

So, next to your code. It looks correct so i can have only couple of suggestions.
- Check that you have called 'setActive' method of AVAudioSession. AVAudioSession should be initialized before Audio Queues (also do not forget to handle interruptions in production code);
- Check that ASBD is correct. Here is example of working one from my project:

``` swift
var asbd = AudioStreamBasicDescription()
asbd.mSampleRate = 8000;
asbd.mFormatID = kAudioFormatLinearPCM
asbd.mFormatFlags = kLinearPCMFormatFlagIsSignedInteger | kLinearPCMFormatFlagIsPacked | kLinearPCMFormatFlagIsNonInterleaved
asbd.mBitsPerChannel = 16
asbd.mChannelsPerFrame = 1
asbd.mBytesPerFrame = asbd.mChannelsPerFrame * 2
asbd.mFramesPerPacket = 1
asbd.mBytesPerPacket = asbd.mFramesPerPacket * asbd.mBytesPerFrame
asbd.mReserved = 0
```
- Check that audio buffer size if big enough;
- Check that PhonographInputQueue has not killed by ARC.

**Comment by donly** [comment]
I found a bug and fixed, it works well now, I will make a pull request later.

**Comment by asfdfdfd** [comment]
Thanks!

**Comment by asfdfdfd** [comment]
Closing this bug for now. If you will have PR do not hesitate to write here.
